// Las 54 explicaciones de `producto-enteros` que el generador no pudo escribir:
// problemas de contexto, sustitución de variables, precedencia y operaciones
// mixtas. Van a mano porque cada una enseña algo distinto, pero mantienen el
// criterio del generador: nombrar la regla antes de dar el número.
export const A_MANO = {
  127: "Si a = −3, entonces −a = 3. La expresión queda (−3) × 3: un solo factor negativo, así que el resultado es negativo. Sin signos daría 9; con el signo, −9.",
  128: "Si a = 6, entonces −a = −6. La expresión queda (−6) × (−6): dos factores negativos que se emparejan, así que el resultado es positivo. Resultado: 36.",
  168: "El paréntesis manda: primero 3² = 9, y el signo de fuera se aplica después. Por eso −(3²) = −9. Compáralo con (−3)², donde el negativo sí entra en la potencia y el resultado es 9.",
  169: "Primero la potencia, 2³ = 8; el signo de fuera queda para el final. Así que −(2³) = −8.",
  176: "(−6)² = 36, porque los dos negativos se emparejan. Luego 36 ÷ (−4) = −9: signos distintos, cociente negativo. Multiplicar por 1 no cambia nada, así que el resultado es −9.",

  190: "Bajar es negativo: cada hora aporta −3 °C. Cinco horas son cinco veces lo mismo, y sumar cinco veces −3 es multiplicar: 5 × (−3) = −15 °C.",
  191: "Descender cuenta como negativo: −4 m cada minuto. En seis minutos, 6 × (−4) = −24, o sea 24 m bajo la superficie.",
  192: "Perder es negativo: −500 cada día. En siete días, 7 × (−500) = −3500.",
  193: "Cada paso atrás vale −2. Ocho pasos son 8 × (−2) = −16.",
  194: "Subir es positivo: 120 m cada segundo. En 5 s, 5 × 120 = 600 m. No hay ningún factor negativo, así que el resultado es positivo.",
  195: "Que la deuda aumente $200 significa que el saldo cambia en −200 cada mes. En cuatro meses, 4 × (−200) = −800.",
  196: "Retroceder es negativo: −15 km por hora. En 3 h, 3 × (−15) = −45.",
  197: "Subir es positivo: +2 °C por hora. En nueve horas, 9 × 2 = 18 °C.",
  198: "Baja 8 m cada 2 minutos, así que en 6 minutos hay tres tramos: 3 × (−8) = −24 m.",
  199: "Ganar es positivo: +50 por día. En diez días, 10 × 50 = 500. Sin factores negativos, el resultado es positivo.",
  200: "Cada error resta 3 puntos, es decir aporta −3. Con siete errores, 7 × (−3) = −21.",
  201: "Cada 10 m de descenso suman 4 atm, y en 30 m hay tres tramos: 3 × 4 = 12 atm. La presión sube aunque la profundidad se mida como negativa: son dos cosas distintas.",
  202: "Cada semana aporta −5 días de retraso. En cuatro semanas, 4 × (−5) = −20.",
  203: "Cada caja aporta −3 kg. Seis cajas: 6 × (−3) = −18.",
  204: "El doble de 4 °C son 8 °C, y bajar es negativo: −8 °C por noche. En tres noches, 3 × (−8) = −24 °C.",
  205: "Bajar es negativo: −2 pisos por segundo. En ocho segundos, 8 × (−2) = −16.",
  206: "Disminuir es negativo: −150 por semana. En seis semanas, 6 × (−150) = −900.",
  207: "Si el norte es positivo, el sur es negativo: −5 km por hora. En 4 h, 4 × (−5) = −20 km.",
  208: "Profundizar es bajar, así que cada semana aporta −7 m. En cinco semanas, 5 × (−7) = −35 m: treinta y cinco metros más abajo.",
  209: "Cada acierto suma 4 puntos. Con veinte aciertos, 20 × 4 = 80. Todos los factores son positivos.",
  210: "Cada tropiezo lo devuelve 6 m, o sea −6. Con cinco tropiezos, 5 × (−6) = −30.",
  211: "Que la deuda crezca $300 es un cambio de −300 en el saldo cada mes. En cinco meses, 5 × (−300) = −1500.",
  212: "Bajar es negativo: −2 °C por hora. En doce horas, 12 × (−2) = −24 °C.",
  213: "Descender es negativo: −300 m por minuto. En cuatro minutos, 4 × (−300) = −1200 m.",
  214: "Son tres factores y los tres positivos: 15 piezas por hora, $8 por pieza y 6 horas. 15 × 8 × 6 = 720.",
  215: "Cada falta resta 12 puntos, o sea −12. En cinco faltas, 5 × (−12) = −60.",
  216: "La velocidad ya viene con signo: −7200 km por hora. En 3 h, 3 × (−7200) = −21600.",
  217: "Bajar es negativo: −25 por día. En ocho días, 8 × (−25) = −200.",
  218: "Cada piso subterráneo aporta −3 m. Ocho pisos abajo: 8 × (−3) = −24 m.",
  219: "Cada día de entrenamiento aporta un déficit de −500 kcal. Dejar de entrenar cuatro días quita cuatro veces ese déficit: (−500) × (−4) = 2000. Los dos negativos se emparejan y el resultado es positivo.",

  220: "Sustituyendo: (−2) × 3. Un solo factor negativo, así que el producto es negativo: −6.",
  221: "Sustituyendo: (−4) × (−5). Dos factores negativos que se emparejan: el producto es positivo, 20.",
  222: "x² es x × x, o sea (−3) × (−3). Los dos negativos se emparejan: 9.",
  223: "x³ es x × x × x, o sea (−3) × (−3) × (−3). Tres negativos: sobra uno sin pareja, así que el resultado es negativo, −27.",
  224: "a² = (−1) × (−1) = 1, y b³ = (−1) × (−1) × (−1) = −1. El producto es 1 × (−1) = −1. En total hay cinco factores negativos, que es impar.",

  227: "Los negativos se cancelan de dos en dos. Si la cantidad es par no sobra ninguno y el producto es positivo; si es impar sobra uno y el producto es negativo.",
  228: "(−3)⁴ son cuatro factores negativos, y cuatro es par: se emparejan todos y el resultado es positivo. Como 3⁴ = 81, el resultado es 81.",
  229: "(−3)⁵ son cinco factores negativos, y cinco es impar: sobra uno sin pareja. Como 3⁵ = 243, el resultado es −243.",
  231: "Un producto sale negativo sólo cuando queda un negativo sin pareja. Con dos factores eso ocurre exactamente cuando uno es positivo y el otro negativo.",
  232: "Con dos factores el producto es positivo cuando los negativos se emparejan: o los dos son negativos, o ninguno lo es. En los dos casos comparten signo.",

  238: "Si a = −5, entonces −a = 5, y el negativo desaparece antes de elevar. Queda 5 × 5 = 25.",
  239: "Aquí la potencia va primero: a² = (−5) × (−5) = 25, y el signo de fuera se aplica después, así que −a² = −25. Compáralo con (−a)², que da 25: el paréntesis cambia el resultado.",
  240: "Primero los productos: (−3) × (−4) = 12, con los dos negativos emparejados, y (−2) × 5 = −10, con uno solo. Después la suma: 12 + (−10) = 2.",
  241: "2 × (−6) = −12 y (−3) × (−4) = 12. Al sumarlos se cancelan: −12 + 12 = 0.",
  242: "(−5) × 3 = −15 y (−2) × (−7) = 14. Queda −15 − 14 = −29: restar 14 aleja todavía más del cero.",
  243: "(−4)² = 16, porque los dos negativos se emparejan, y (−2)³ = −8, porque son tres. Restar −8 es sumar 8: 16 + 8 = 24.",
  244: "(−2)² = 4 y (−3)² = 9: los dos positivos, porque los negativos van de dos en dos. Entonces 3 × 4 = 12 y 2 × 9 = 18, y 12 − 18 = −6.",
  245: "Las potencias de −1 alternan: (−1)¹ = −1, (−1)² = 1, (−1)³ = −1, (−1)⁴ = 1. Sumando, −1 + 1 − 1 + 1 = 0.",
  246: "(−a)⁶ es (−a) multiplicado seis veces, así que hay seis factores negativos. Seis es par, se emparejan todos y el resultado es positivo, valga lo que valga a > 0.",
};
